version: '3.8'

services:
  pizza-wallet:
    container_name: esi4-web-app
    build:
      context: .
      dockerfile: Dockerfile.react.start
    volumes:
      - ./src:/./src
    ports:
      - 3000:3000
    environment:
       - CHOKIDAR_USEPOLLING=true